{
 "title": "Istio Performance Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Performance Dashboard Notes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Performance Dashboard README",
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "The charts on this dashboard are intended to show Istio main components cost in terms of resources utilization under steady load.\n\n- **vCPU / 1k rps:** shows vCPU utilization by the main Istio components normalized by 1000 requests/second. When idle or low traffic, this chart will be blank. The curve for istio-proxy refers to the services sidecars only.\n- **vCPU:** vCPU utilization by Istio components, not normalized.\n- **Memory:** memory footprint for the components. Telemetry and policy are normalized by 1k rps, and no data is shown  when there is no traffic. For ingress and istio-proxy, the data is per instance.\n- **Bytes transferred / sec:** shows the number of bytes flowing through each Istio component.\n\n\n"
   }
  },
  {
   "title": "vCPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "vCPU / 1k rps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(irate(container_cpu_usage_seconds_total{pod=~\"istio-ingressgateway-.*\",container=\"istio-proxy\"}[1m])) / (round(sum(irate(istio_requests_total{source_workload=\"istio-ingressgateway\", reporter=\"source\"}[1m])), 0.001)/1000))",
     "legendFormat": "istio-ingressgateway"
    },
    {
     "expr": "(sum(irate(container_cpu_usage_seconds_total{namespace!=\"istio-system\",container=\"istio-proxy\"}[1m]))/ (round(sum(irate(istio_requests_total[1m])), 0.001)/1000))/ (sum(irate(istio_requests_total{source_workload=\"istio-ingressgateway\"}[1m])) >bool 10)",
     "legendFormat": "istio-proxy"
    }
   ]
  },
  {
   "title": "vCPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"istio-ingressgateway-.*\",container=\"istio-proxy\"}[1m]))",
     "legendFormat": "istio-ingressgateway"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace!=\"istio-system\",container=\"istio-proxy\"}[1m]))",
     "legendFormat": "istio-proxy"
    }
   ]
  },
  {
   "title": "Memory and Data Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"istio-ingressgateway-.*\"}) / count(container_memory_working_set_bytes{pod=~\"istio-ingressgateway-.*\",container!=\"POD\"})",
     "legendFormat": "per istio-ingressgateway"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace!=\"istio-system\",container=\"istio-proxy\"}) / count(container_memory_working_set_bytes{namespace!=\"istio-system\",container=\"istio-proxy\"})",
     "legendFormat": "per istio proxy"
    }
   ]
  },
  {
   "title": "Bytes transferred / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(istio_response_bytes_sum{source_workload=\"istio-ingressgateway\", reporter=\"source\"}[1m]))",
     "legendFormat": "istio-ingressgateway"
    },
    {
     "expr": "sum(irate(istio_response_bytes_sum{source_workload_namespace!=\"istio-system\", reporter=\"source\"}[1m])) + sum(irate(istio_request_bytes_sum{source_workload_namespace!=\"istio-system\", reporter=\"source\"}[1m]))",
     "legendFormat": "istio-proxy"
    }
   ]
  },
  {
   "title": "Istio Component Versions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Istio Components by Version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(istio_build) by (component, tag)",
     "legendFormat": "{{ component }}: {{ tag }}"
    }
   ]
  },
  {
   "title": "Proxy Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"istio-proxy\"})",
     "legendFormat": "Total (k8s)"
    }
   ]
  },
  {
   "title": "vCPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"istio-proxy\"}[1m]))",
     "legendFormat": "Total (k8s)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{container=\"istio-proxy\"})",
     "legendFormat": "Total (k8s)"
    }
   ]
  },
  {
   "title": "Istiod Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{app=\"istiod\"}",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "process_resident_memory_bytes{app=\"istiod\"}",
     "legendFormat": "Resident Memory"
    },
    {
     "expr": "go_memstats_alloc_bytes{app=\"istiod\"}",
     "legendFormat": "Alloc"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{app=\"istiod\"}",
     "legendFormat": "Heap in-use"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{app=\"istiod\"}",
     "legendFormat": "Stack in-use"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container=~\"discovery|istio-proxy\", pod=~\"istiod-.*\"})",
     "legendFormat": "Total (k8s)"
    },
    {
     "expr": "container_memory_working_set_bytes{container=~\"discovery|istio-proxy\", pod=~\"istiod-.*\"}",
     "legendFormat": "{{ container }} (k8s)"
    }
   ]
  },
  {
   "title": "vCPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"discovery|istio-proxy\", pod=~\"istiod-.*\"}[1m]))",
     "legendFormat": "Total (k8s)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"discovery|istio-proxy\", pod=~\"istiod-.*\"}[1m])) by (container)",
     "legendFormat": "{{ container }} (k8s)"
    },
    {
     "expr": "irate(process_cpu_seconds_total{app=\"istiod\"}[1m])",
     "legendFormat": "pilot (self-reported)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{ container=~\"discovery|istio-proxy\", pod=~\"istiod-.*\"}",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{app=\"istiod\"}",
     "legendFormat": "Number of Goroutines"
    }
   ]
  }
 ]
}
{
 "title": "Istio Control Plane Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Deployed Versions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pilot Versions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(istio_build{component=\"pilot\"}) by (tag)",
     "legendFormat": "{{ tag }}"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{app=\"istiod\"}",
       "legendFormat": "Virtual Memory"
      },
      {
       "expr": "process_resident_memory_bytes{app=\"istiod\"}",
       "legendFormat": "Resident Memory"
      },
      {
       "expr": "go_memstats_alloc_bytes{app=\"istiod\"}",
       "legendFormat": "Alloc"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{app=\"istiod\"}",
       "legendFormat": "Heap in-use"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{app=\"istiod\"}",
       "legendFormat": "Stack in-use"
      },
      {
       "expr": "container_memory_working_set_bytes{container=~\"discovery\", pod=~\"istiod-.*|istio-pilot-.*\"}",
       "legendFormat": "Discovery (container)"
      },
      {
       "expr": "container_memory_working_set_bytes{container=~\"istio-proxy\", pod=~\"istiod-.*|istio-pilot-.*\"}",
       "legendFormat": "Sidecar (container)"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"discovery\", pod=~\"istiod-.*|istio-pilot-.*\"}[1m]))",
       "legendFormat": "Discovery (container)"
      },
      {
       "expr": "irate(process_cpu_seconds_total{app=\"istiod\"}[1m])",
       "legendFormat": "Discovery (process)"
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"istio-proxy\", pod=~\"istiod-.*|istio-pilot-.*\"}[1m]))",
       "legendFormat": "Sidecar (container)"
      }
     ]
    },
    {
     "title": "Disk",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_fs_usage_bytes{container=\"discovery\", pod=~\"istiod-.*|istio-pilot-.*\"}",
       "legendFormat": "Discovery"
      },
      {
       "expr": "container_fs_usage_bytes{container=\"istio-proxy\", pod=~\"istiod-.*|istio-pilot-.*\"}",
       "legendFormat": "Sidecar"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{app=\"istiod\"}",
       "legendFormat": "Number of Goroutines"
      }
     ]
    }
   ]
  },
  {
   "title": "Pilot Push Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Pilot Pushes",
     "type": "timeseries",
     "description": "Shows the rate of pilot pushes",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(pilot_xds_pushes{type=\"cds\"}[1m]))",
       "legendFormat": "Cluster"
      },
      {
       "expr": "sum(irate(pilot_xds_pushes{type=\"eds\"}[1m]))",
       "legendFormat": "Endpoints"
      },
      {
       "expr": "sum(irate(pilot_xds_pushes{type=\"lds\"}[1m]))",
       "legendFormat": "Listeners"
      },
      {
       "expr": "sum(irate(pilot_xds_pushes{type=\"rds\"}[1m]))",
       "legendFormat": "Routes"
      },
      {
       "expr": "sum(irate(pilot_xds_pushes{type=\"sds\"}[1m]))",
       "legendFormat": "Secrets"
      },
      {
       "expr": "sum(irate(pilot_xds_pushes{type=\"nds\"}[1m]))",
       "legendFormat": "Nametables"
      }
     ]
    },
    {
     "title": "Pilot Errors",
     "type": "timeseries",
     "description": "Captures a variety of pilot errors",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(pilot_xds_cds_reject{app=\"istiod\"}) or (absent(pilot_xds_cds_reject{app=\"istiod\"}) - 1)",
       "legendFormat": "Rejected CDS Configs"
      },
      {
       "expr": "sum(pilot_xds_eds_reject{app=\"istiod\"}) or (absent(pilot_xds_eds_reject{app=\"istiod\"}) - 1)",
       "legendFormat": "Rejected EDS Configs"
      },
      {
       "expr": "sum(pilot_xds_rds_reject{app=\"istiod\"}) or (absent(pilot_xds_rds_reject{app=\"istiod\"}) - 1)",
       "legendFormat": "Rejected RDS Configs"
      },
      {
       "expr": "sum(pilot_xds_lds_reject{app=\"istiod\"}) or (absent(pilot_xds_lds_reject{app=\"istiod\"}) - 1)",
       "legendFormat": "Rejected LDS Configs"
      },
      {
       "expr": "sum(rate(pilot_xds_write_timeout{app=\"istiod\"}[1m]))",
       "legendFormat": "Write Timeouts"
      },
      {
       "expr": "sum(rate(pilot_total_xds_internal_errors{app=\"istiod\"}[1m]))",
       "legendFormat": "Internal Errors"
      },
      {
       "expr": "sum(rate(pilot_total_xds_rejects{app=\"istiod\"}[1m]))",
       "legendFormat": "Config Rejection Rate"
      },
      {
       "expr": "sum(rate(pilot_xds_push_context_errors{app=\"istiod\"}[1m]))",
       "legendFormat": "Push Context Errors"
      },
      {
       "expr": "sum(rate(pilot_xds_write_timeout{app=\"istiod\"}[1m]))",
       "legendFormat": "Push Timeouts"
      }
     ]
    },
    {
     "title": "Proxy Push Time",
     "type": "timeseries",
     "description": "Shows the total time it takes to push a config update to a proxy",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(pilot_proxy_convergence_time_bucket[1m])) by (le))",
       "legendFormat": "p50 "
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(pilot_proxy_convergence_time_bucket[1m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(pilot_proxy_convergence_time_bucket[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(pilot_proxy_convergence_time_bucket[1m])) by (le))",
       "legendFormat": "p99.9"
      }
     ]
    },
    {
     "title": "Conflicts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pilot_conflict_inbound_listener{app=\"istiod\"}",
       "legendFormat": "Inbound Listeners"
      },
      {
       "expr": "pilot_conflict_outbound_listener_tcp_over_current_tcp{app=\"istiod\"}",
       "legendFormat": "Outbound Listeners (tcp over current tcp)"
      }
     ]
    },
    {
     "title": "ADS Monitoring",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(pilot_virt_services{app=\"istiod\"})",
       "legendFormat": "Virtual Services"
      },
      {
       "expr": "avg(pilot_services{app=\"istiod\"})",
       "legendFormat": "Services"
      },
      {
       "expr": "sum(pilot_xds{app=\"istiod\"}) by (pod)",
       "legendFormat": "Connected Endpoints {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Envoy Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Envoy Details",
     "type": "timeseries",
     "description": "Shows details about Envoy proxies in the mesh",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(envoy_cluster_upstream_cx_total{cluster_name=\"xds-grpc\"}[1m]))",
       "legendFormat": "XDS Connections"
      },
      {
       "expr": "sum(irate(envoy_cluster_upstream_cx_connect_fail{cluster_name=\"xds-grpc\"}[1m]))",
       "legendFormat": "XDS Connection Failures"
      },
      {
       "expr": "sum(increase(envoy_server_hot_restart_epoch[1m]))",
       "legendFormat": "Envoy Restarts"
      }
     ]
    },
    {
     "title": "XDS Active Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(envoy_cluster_upstream_cx_active{cluster_name=\"xds-grpc\"})",
       "legendFormat": "XDS Active Connections"
      }
     ]
    },
    {
     "title": "XDS Requests Size",
     "type": "timeseries",
     "description": "Shows the size of XDS requests and responses",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "max(rate(envoy_cluster_upstream_cx_rx_bytes_total{cluster_name=\"xds-grpc\"}[1m]))",
       "legendFormat": "XDS Response Bytes Max"
      },
      {
       "expr": "quantile(0.5, rate(envoy_cluster_upstream_cx_rx_bytes_total{cluster_name=\"xds-grpc\"}[1m]))",
       "legendFormat": "XDS Response Bytes Average"
      },
      {
       "expr": "max(rate(envoy_cluster_upstream_cx_tx_bytes_total{cluster_name=\"xds-grpc\"}[1m]))",
       "legendFormat": "XDS Request Bytes Max"
      },
      {
       "expr": "quantile(.5, rate(envoy_cluster_upstream_cx_tx_bytes_total{cluster_name=\"xds-grpc\"}[1m]))",
       "legendFormat": "XDS Request Bytes Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Webhooks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Configuration Validation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(galley_validation_passed[1m]))",
       "legendFormat": "Validations (Success)"
      },
      {
       "expr": "sum(rate(galley_validation_failed[1m]))",
       "legendFormat": "Validation (Failure)"
      }
     ]
    },
    {
     "title": "Sidecar Injection",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(sidecar_injection_success_total[1m]))",
       "legendFormat": "Injections (Success)"
      },
      {
       "expr": "sum(rate(sidecar_injection_failure_total[1m]))",
       "legendFormat": "Injections (Failure)"
      }
     ]
    }
   ]
  }
 ]
}